"""changed from zip code to zip codeS

Revision ID: 07520852b5f8
Revises: b77c71dd9930
Create Date: 2025-11-10 18:48:41.573078

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07520852b5f8'
down_revision: Union[str, Sequence[str], None] = 'b77c71dd9930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('serviceable_zip_codes', sa.ARRAY(sa.INTEGER()), nullable=True))
    op.drop_column('delivery_partner', 'serviceable_zip_code')
    op.alter_column('shipment', 'estimated_delivery',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'estimated_delivery',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('delivery_partner', sa.Column('serviceable_zip_code', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('delivery_partner', 'serviceable_zip_codes')
    # ### end Alembic commands ###
