"""sanity check

Revision ID: 6478ef347519
Revises: 07520852b5f8
Create Date: 2025-11-10 19:45:28.611002

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6478ef347519'
down_revision: Union[str, Sequence[str], None] = '07520852b5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('address', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
