"""Make seller.address and seller.zip_code nullable

Revision ID: 8a5f31623591
Revises: ea5b76a6f7e6
Create Date: 2025-11-14 21:00:06.923309

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5f31623591'
down_revision: Union[str, Sequence[str], None] = 'ea5b76a6f7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'review', 'shipment', ['shipment_id'], ['id'])
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'servicable_location', 'delivery_partner', ['partner_id'], ['id'])
    op.drop_index(op.f('idx_tag_name_unique'), table_name='tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tag_name_unique'), 'tag', ['name'], unique=True)
    op.drop_constraint(None, 'servicable_location', type_='foreignkey')
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'review', type_='foreignkey')
    # ### end Alembic commands ###
