"""add client contact in shipment

Revision ID: a27f1eb7364c
Revises: 51e3671f5f3c
Create Date: 2025-11-11 18:28:23.004992

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27f1eb7364c'
down_revision: Union[str, Sequence[str], None] = '51e3671f5f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_partner', 'client_contact_phone')
    op.drop_column('delivery_partner', 'client_contact_email')
    op.add_column('shipment', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment', sa.Column('client_contact_phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'client_contact_phone')
    op.drop_column('shipment', 'client_contact_email')
    op.add_column('delivery_partner', sa.Column('client_contact_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('delivery_partner', sa.Column('client_contact_phone', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
