"""add tag

Revision ID: e2e1e0bf0f17
Revises: c4f9b5a00480
Create Date: 2025-11-14 15:05:20.826361

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from app.database.models import TagName

# revision identifiers, used by Alembic.
revision: str = 'e2e1e0bf0f17'
down_revision: Union[str, Sequence[str], None] = 'c4f9b5a00480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shipment_tag_tag_id_fkey'), 'shipment_tag', type_='foreignkey')
    op.create_foreign_key(None, 'shipment_tag', 'tag', ['tag_id'], ['id'])
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTROLLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'),
               existing_nullable=False,
               # PostgreSQL needs an explicit USING clause to cast existing
               # varchar values to the new enum type.
               postgresql_using="name::tagname",
               )
    # ### end Alembic commands ###

    ### Add tag entries in the database
    # Insert one row per TagName with a unique instruction
    instructions = {
        TagName.EXPRESS: "Prioritize expedited handling; use fastest route.",
        TagName.STANDARD: "Process under standard SLA and routing.",
        TagName.FRAGILE: "Handle with care; add cushioning; avoid stacking.",
        TagName.HEAVY: "Use lifting aid or team lift; verify weight limits.",
        TagName.INTERNATIONAL: "Verify customs docs and HS codes; apply duties.",
        TagName.DOMESTIC: "Use domestic routing and standard documentation.",
        TagName.TEMPERATURE_CONTROLLED: "Maintain required temperature; preserve cold chain.",
        TagName.GIFT: "Exclude pricing; include gift note; neutral packaging.",
        TagName.RETURN: "Attach RMA; route to returns center; inspect on receipt.",
        TagName.DOCUMENTS: "Use document pouch; do not fold; require signature.",
    }

    # Use the migration bind to execute parameterized statements. `op.execute`
    # in this context does not accept a separate params arg the way we used it,
    # so get the connection and call its execute which accepts params.
    bind = op.get_bind()
    for name, instruction in instructions.items():
        # `name` is a TagName enum member. The DB enum type was created
        # with labels matching the enum member *names* (e.g. 'EXPRESS'), so
        # insert the member name rather than its value ('express').
        bind.execute(
            sa.text(
                "INSERT INTO tag (id, name, instructions) VALUES (gen_random_uuid(), :name, :instruction)"
            ),
            {"name": name.name, "instruction": instruction},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'name',
               existing_type=sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTROLLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="name::text",
               )
    op.drop_constraint(None, 'shipment_tag', type_='foreignkey')
    op.create_foreign_key(op.f('shipment_tag_tag_id_fkey'), 'shipment_tag', 'shipment', ['tag_id'], ['id'])
    # ### end Alembic commands ###
