"""add user email_verified

Revision ID: e887138e3a51
Revises: a27f1eb7364c
Create Date: 2025-11-12 18:38:23.666545

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e887138e3a51'
down_revision: Union[str, Sequence[str], None] = 'a27f1eb7364c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add as nullable first to avoid NotNullViolation on existing rows
    op.add_column('delivery_partner', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('seller', sa.Column('email_verified', sa.Boolean(), nullable=True))

    # Backfill existing rows with False where NULL
    op.execute("UPDATE delivery_partner SET email_verified = false WHERE email_verified IS NULL")
    op.execute("UPDATE seller SET email_verified = false WHERE email_verified IS NULL")

    # Now make the columns NOT NULL
    op.alter_column('delivery_partner', 'email_verified', nullable=False)
    op.alter_column('seller', 'email_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'email_verified')
    op.drop_column('delivery_partner', 'email_verified')
    # ### end Alembic commands ###
