"""from the top

Revision ID: ea5b76a6f7e6
Revises: 20251114_fix_shipmenttag_fk
Create Date: 2025-11-14 15:34:15.263889

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea5b76a6f7e6'
down_revision: Union[str, Sequence[str], None] = '20251114_fix_shipmenttag_fk'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('DROP TABLE IF EXISTS reviews'))
    op.execute(sa.text('ALTER TABLE delivery_partner DROP COLUMN IF EXISTS serviceable_zip_codes'))
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shipment', 'estimated_delivery',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.execute(sa.text("ALTER TABLE tag ADD COLUMN IF NOT EXISTS instruction VARCHAR NOT NULL"))
    op.execute(sa.text('ALTER TABLE tag DROP COLUMN IF EXISTS instructions'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('instructions', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tag', 'instruction')
    op.alter_column('shipment', 'estimated_delivery',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('delivery_partner', sa.Column('serviceable_zip_codes', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], name=op.f('reviews_shipment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey'))
    )
    # ### end Alembic commands ###
